package com.devsai.model;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webapp/static/proto/upload.proto

public final class UploadMsg {
  private UploadMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UploadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Upload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string filename = 1;</code>
     */
    boolean hasFilename();
    /**
     * <code>required string filename = 1;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>required string filename = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>required int32 currchunk = 2;</code>
     */
    boolean hasCurrchunk();
    /**
     * <code>required int32 currchunk = 2;</code>
     */
    int getCurrchunk();

    /**
     * <code>required int32 chunks = 3;</code>
     */
    boolean hasChunks();
    /**
     * <code>required int32 chunks = 3;</code>
     */
    int getChunks();

    /**
     * <code>required int32 uid = 4;</code>
     */
    boolean hasUid();
    /**
     * <code>required int32 uid = 4;</code>
     */
    int getUid();

    /**
     * <code>required bytes upload_file = 5;</code>
     */
    boolean hasUploadFile();
    /**
     * <code>required bytes upload_file = 5;</code>
     */
    com.google.protobuf.ByteString getUploadFile();
  }
  /**
   * Protobuf type {@code Upload}
   */
  public static final class Upload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Upload)
      UploadOrBuilder {
    // Use Upload.newBuilder() to construct.
    private Upload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Upload(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Upload defaultInstance;
    public static Upload getDefaultInstance() {
      return defaultInstance;
    }

    public Upload getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Upload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              filename_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currchunk_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              chunks_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              uid_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              uploadFile_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UploadMsg.internal_static_Upload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UploadMsg.internal_static_Upload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UploadMsg.Upload.class, UploadMsg.Upload.Builder.class);
    }

    public static com.google.protobuf.Parser<Upload> PARSER =
        new com.google.protobuf.AbstractParser<Upload>() {
      public Upload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Upload(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Upload> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private java.lang.Object filename_;
    /**
     * <code>required string filename = 1;</code>
     */
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string filename = 1;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string filename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRCHUNK_FIELD_NUMBER = 2;
    private int currchunk_;
    /**
     * <code>required int32 currchunk = 2;</code>
     */
    public boolean hasCurrchunk() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 currchunk = 2;</code>
     */
    public int getCurrchunk() {
      return currchunk_;
    }

    public static final int CHUNKS_FIELD_NUMBER = 3;
    private int chunks_;
    /**
     * <code>required int32 chunks = 3;</code>
     */
    public boolean hasChunks() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 chunks = 3;</code>
     */
    public int getChunks() {
      return chunks_;
    }

    public static final int UID_FIELD_NUMBER = 4;
    private int uid_;
    /**
     * <code>required int32 uid = 4;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 uid = 4;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int UPLOAD_FILE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString uploadFile_;
    /**
     * <code>required bytes upload_file = 5;</code>
     */
    public boolean hasUploadFile() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes upload_file = 5;</code>
     */
    public com.google.protobuf.ByteString getUploadFile() {
      return uploadFile_;
    }

    private void initFields() {
      filename_ = "";
      currchunk_ = 0;
      chunks_ = 0;
      uid_ = 0;
      uploadFile_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFilename()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrchunk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChunks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUploadFile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilenameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, currchunk_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, chunks_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, uid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, uploadFile_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilenameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currchunk_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, chunks_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, uid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, uploadFile_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UploadMsg.Upload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UploadMsg.Upload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UploadMsg.Upload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UploadMsg.Upload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UploadMsg.Upload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UploadMsg.Upload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static UploadMsg.Upload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static UploadMsg.Upload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static UploadMsg.Upload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UploadMsg.Upload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UploadMsg.Upload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Upload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Upload)
        UploadMsg.UploadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UploadMsg.internal_static_Upload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UploadMsg.internal_static_Upload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UploadMsg.Upload.class, UploadMsg.Upload.Builder.class);
      }

      // Construct using UploadMsg.Upload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        currchunk_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        chunks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        uploadFile_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UploadMsg.internal_static_Upload_descriptor;
      }

      public UploadMsg.Upload getDefaultInstanceForType() {
        return UploadMsg.Upload.getDefaultInstance();
      }

      public UploadMsg.Upload build() {
        UploadMsg.Upload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UploadMsg.Upload buildPartial() {
        UploadMsg.Upload result = new UploadMsg.Upload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filename_ = filename_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currchunk_ = currchunk_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chunks_ = chunks_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uploadFile_ = uploadFile_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UploadMsg.Upload) {
          return mergeFrom((UploadMsg.Upload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UploadMsg.Upload other) {
        if (other == UploadMsg.Upload.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          bitField0_ |= 0x00000001;
          filename_ = other.filename_;
          onChanged();
        }
        if (other.hasCurrchunk()) {
          setCurrchunk(other.getCurrchunk());
        }
        if (other.hasChunks()) {
          setChunks(other.getChunks());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasUploadFile()) {
          setUploadFile(other.getUploadFile());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFilename()) {
          
          return false;
        }
        if (!hasCurrchunk()) {
          
          return false;
        }
        if (!hasChunks()) {
          
          return false;
        }
        if (!hasUid()) {
          
          return false;
        }
        if (!hasUploadFile()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UploadMsg.Upload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UploadMsg.Upload) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object filename_ = "";
      /**
       * <code>required string filename = 1;</code>
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }

      private int currchunk_ ;
      /**
       * <code>required int32 currchunk = 2;</code>
       */
      public boolean hasCurrchunk() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 currchunk = 2;</code>
       */
      public int getCurrchunk() {
        return currchunk_;
      }
      /**
       * <code>required int32 currchunk = 2;</code>
       */
      public Builder setCurrchunk(int value) {
        bitField0_ |= 0x00000002;
        currchunk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 currchunk = 2;</code>
       */
      public Builder clearCurrchunk() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currchunk_ = 0;
        onChanged();
        return this;
      }

      private int chunks_ ;
      /**
       * <code>required int32 chunks = 3;</code>
       */
      public boolean hasChunks() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 chunks = 3;</code>
       */
      public int getChunks() {
        return chunks_;
      }
      /**
       * <code>required int32 chunks = 3;</code>
       */
      public Builder setChunks(int value) {
        bitField0_ |= 0x00000004;
        chunks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 chunks = 3;</code>
       */
      public Builder clearChunks() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chunks_ = 0;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>required int32 uid = 4;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 uid = 4;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>required int32 uid = 4;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000008;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uid = 4;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uid_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString uploadFile_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes upload_file = 5;</code>
       */
      public boolean hasUploadFile() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes upload_file = 5;</code>
       */
      public com.google.protobuf.ByteString getUploadFile() {
        return uploadFile_;
      }
      /**
       * <code>required bytes upload_file = 5;</code>
       */
      public Builder setUploadFile(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uploadFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes upload_file = 5;</code>
       */
      public Builder clearUploadFile() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uploadFile_ = getDefaultInstance().getUploadFile();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Upload)
    }

    static {
      defaultInstance = new Upload(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Upload)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Upload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Upload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n webapp/static/proto/upload.proto\"_\n\006Up" +
      "load\022\020\n\010filename\030\001 \002(\t\022\021\n\tcurrchunk\030\002 \002(" +
      "\005\022\016\n\006chunks\030\003 \002(\005\022\013\n\003uid\030\004 \002(\005\022\023\n\013upload" +
      "_file\030\005 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Upload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Upload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Upload_descriptor,
        new java.lang.String[] { "Filename", "Currchunk", "Chunks", "Uid", "UploadFile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
